services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - "./redis-data:/data"
      - ./redis.conf:/redis.conf
    command: redis-server /redis.conf
    environment:
      - REDIS_MAXMEMORY 128mb
    networks:
      - redis

networks:
  redis:
    driver: bridge
