kafka:
  servers:
    - 127.0.0.1:9092
  group: streamA
  topic-subscriptions:
    - TransferCreateEvent
    - TransferExternalCompletedEvent
    - TransferExternalFailedEvent

db:
  driver: mysql
  host: 127.0.0.1
  port: 3306
  username: local_user
  password: p@ssw0rd
  database: local_db