kafka:
  servers:
    - localhost:9092
  group: streamA
  topic-subscriptions:
    - TransferCreateEvent
    - TransferExternalCompletedEvent
    - TransferExternalFailedEvent

db:
  driver: mysql
  host: localhost
  port: 3306
  username: local_user
  password: p@ssw0rd
  database: local_db

redis:
  host: localhost
  port: 6379
