services:
  zookeeper:
    image: zookeeper:latest
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - ./zookeeper:/data
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - kafka-network

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    volumes:
      - ./kafka:/bitnami/kafka/data
    depends_on:
      - zookeeper
    environment:
      - BITNAMI_DEBUG=true
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    networks:
      - kafka-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - "./redis-data:/data"
    environment:
      - REDIS_MAXMEMORY 128mb

  db:
    image: mysql:9.0.1
    restart: always
    environment:
      MYSQL_DATABASE: 'local_db'
      MYSQL_USER: 'local_user'
      MYSQL_PASSWORD: 'p@ssw0rd'
      MYSQL_ROOT_PASSWORD: 'p@ssw0rd'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - local_db:/var/lib/mysql
      - ./docker:/docker-entrypoint-initdb.d

networks:
  kafka-network:
